fun main() {
    println("--- Day 1: Historian Hysteria ---")
    day01.main()
    println("--- Day 2: Red-Nosed Reports ---")
    day02.main()
    println("--- Day 3: Mull It Over ---")
    day03.main()
    println("--- Day 4: Ceres Search ---")
    day04.main()
    println("--- Day 5: Print Queue ---")
    day05.main()
    println("--- Day 6: Guard Gallivant ---")
    day06.main()
    println("--- Day 7: Bridge Repair ---")
    day07.main()
    println("--- Day 8: Resonant Collinearity ---")
    day08.main()
    println("--- Day 9: Disk Fragmenter ---")
    day09.main()
    println("--- Day 10: Hoof It ---")
    day10.main()
    println("--- Day 11: Plutonian Pebbles ---")
    day11.main()
    println("--- Day 12: Garden Groups ---")
    day12.main()
    println("--- Day 13: Claw Contraption ---")
    day13.main()
    println("--- Day 14: Restroom Redoubt ---")
    day14.main()
    println("--- Day 15: Warehouse Woes ---")
    day15.main()
    println("--- Day 16: Reindeer Maze ---")
    day16.main()
    println("--- Day 17: Chronospatial Computer ---")
    day17.main()
    println("--- Day 18: RAM Run ---")
    day18.main()
}
