fun main() {
    println("--- Day 1: Historian Hysteria ---")
    day01.main()
    println("--- Day 2: Red-Nosed Reports ---")
    day02.main()
    println("--- Day 3: Mull It Over ---")
    day03.main()
    println("--- Day 4: Ceres Search ---")
    day04.main()
    println("--- Day 5: Print Queue ---")
    day05.main()
    println("--- Day 6: Guard Gallivant ---")
    day06.main()
    println("--- Day 7: Bridge Repair ---")
    day07.main()
    println("--- Day 8: Resonant Collinearity ---")
    day07.main()
}
